### ISSUE TITLE
HTML escape

### ISSUE THREAD

**Issue by vmihailenco** [ketilovre/angular-json-print#1]
This plugin should escape HTML inside the JSON object. Otherwise that HTML is rendered by browser.

**Comment by vmihailenco** [comment]
Probably the issue is that JSON string contains `:`. Honestly I don't understand why you exclude `:` in string regex `/("[^:].*")/`.

**Comment by vmihailenco** [comment]
To reproduce try this JSON: `"colon": "\: html goes <here> \"bar"`.

**Comment by ketilovre** [comment]
Hi,

Thanks for your feedback. I've updated the package to `1.0.4`. I hope this solves your problem.
