### ISSUE TITLE
Update rendered JSON when the underlying object changes.

### ISSUE THREAD

**Issue by ChrisNoel** [ketilovre/angular-json-print#2]
The watcher in the jsonPrint directive (line 98 in src/json-print.js) only parses the the attrs.jsonPrint object when the value is initially provided, not when it changes. 

I am not sure about other users of this library, but I have encountered use cases where I want the content to update when the object changes. This is achieved by providing a third argument of true to the scope.$watch call on line 98 (see https://docs.angularjs.org/api/ng/type/$rootScope.Scope).

I am going to introduce this change and hopefully it can be pulled into master. I do not believe it will change the library's current functionality, only extend it to suit this case.

**Comment by ketilovre** [comment]
Closed by #3.
